### ISSUE TITLE
This name is from Nigeria

### ISSUE THREAD

**Issue by Obamma001** [jneem/ojo#3]

**Comment by Obamma001** [comment]
[You can come]()![Screenshot_20210807-153436.png](https://user-images.githubusercontent.com/88560884/128616417-de6184fa-f5f8-40c1-98a3-832f51f33c3b.png)

**Comment by jneem** [comment]
Interesting, I didn't know! (It's also the name of a character in "The Wizard of Oz", and it means "eye" in spanish)
